{
  description = "Betty's Personal NixOS Configuration";

  outputs =
    inputs@{
      self,
      nixpkgs,
      disko,
      flake-parts,
      home-manager,
      impermanence,
      nix-index-database,
      nixos-hardware,
      pre-commit-hooks,
      stylix,
      sops-nix,
      zen-browser,
      ...
    }:

    let
      inherit (self) outputs;

      # Variable to hold all overlays in ./overlays
      # By default, nix will check for default.nix within when provided a directory as a path
      overlaySet = import ./overlays { inherit inputs; };
      overlays = [
        overlaySet.additions
        overlaySet.affinity-nix
        overlaySet.bleeding-packages
        overlaySet.stable-packages
      ];

      # Returns nixpkgs.lib including our own lib functions found in ./lib (default.nix)
      # Func that receives system architecture(s)
      # Wraps around recursiveUpdate: https://noogle.dev/f/lib/recursiveUpdate/
      lib =
        system:
        nixpkgs.lib.recursiveUpdate (import ./lib {
          pkgs = mkPkgs system;
          lib = nixpkgs.lib;
        }) nixpkgs.lib;

      # Useful helper to provide a list of system architectures you want an attrSet to be eval'able for
      # Wraps around genAttrs: https://noogle.dev/f/lib/genAttrs/
      # Provides systems as inputs to other functions
      forAllSystems = nixpkgs.lib.genAttrs [
        "x86_64-linux"
        # "aarch64-linux"
      ];

      # Returns the nixpkgs input while adding all overlays
      # Func that receives system architecture(s)
      # In particular, injects the stable package channel as an attr (nixpkgs.stable.pkg)
      mkPkgs =
        system:
        import nixpkgs {
          inherit system overlays;
        };

      # Takes a system architecture, hostname, and a list of modules,
      # outputs a system configuration with common system modules for the platform,
      # all machine-specific configuration for the given hostname,
      # a home-manager configuration for the given hostname,
      # as well as any additional modules passed to the builder function.
      mkNixosConfig =
        system: hostname: extraModules:
        nixpkgs.lib.nixosSystem {
          modules = [
            # Include all machine-specific configuration
            # Each folder in ./machines corresponds to a physical host.
            # These should be generated by an initial nixos install (nixos-generate-config --root /mnt),
            # and stored in the ./machines/<hostname>/ directory,
            # along with a default.nix that loads all files in that directory.
            ./machines/${hostname}

            # Include the Home-Manager configuration for the machine
            # Each file in ./homes corresponds to a physical host.
            # The file should be <hostname>.nix
            # This way the Home-Manager configuration may differ per machine,
            # typically only requiring importing different sets of home modules.
            home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              home-manager.extraSpecialArgs = { inherit inputs; };
              home-manager.users.betty = ./homes/${hostname}.nix;
            }

            # Include shared common system modules
            ./modules/nixos/system/common

            # Static module included to pull in overlays so that the configuration's pkgs
            # are actually modified as expected
            {
              nixpkgs.overlays = overlays;
            }
          ]
          # Always include any extra modules passed to the function
          ++ extraModules; # The ++ operator concatenates two lists
          specialArgs = {
            inherit inputs outputs;
            lib = lib system;
          };
        };
    in
    flake-parts.lib.mkFlake { inherit inputs; } (
      top@{
        config,
        withSystem,
        moduleWithSystem,
        ...
      }:
      {
        # Original Flake logic
        ######################
        flake = {
          # Shorthand for overlays (the output) = overlays (the 'let' variable) ;
          overlays = overlaySet;

          # Provides flake-wide tests to run on evaluation and in devshell
          # Usage: nix flake check
          checks = forAllSystems (system: {
            pre-commit-check = pre-commit-hooks.lib.${system}.run {
              src = ./.;
              hooks = {
                nixfmt-rfc-style.enable = true;
              };
            };
          });

          # Activate a temporary shell environment with extra packages and settings
          # Can be auto-activated using nix-direnv, or loaded from the flake remotely using nix+git
          # Usage (anywhere within the flake): nix develop
          devShells = forAllSystems (
            system:
            let
              pkgs = mkPkgs system;
            in
            {
              default = pkgs.mkShell {
                # Inherit the flake's own checks shellHook to load on shell activation
                inherit (self.checks.${system}.pre-commit-check) shellHook;
                # Environment variables
                EDITOR = "nvim";
                GIT_USER = "0tanh";
                GIT_PASSWORD = "0cba0873c6e66acf1319ca6657e53d14c5529862";
                NIX_CONFIG = ''
                  access-tokens = github.com=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 

                  experimental-features = nix-command flakes
                '';
                # Include packages to be available in the shell env
                packages = with pkgs; [
                  curl
                  git
                  lazygit
                  magic-wormhole
                  nh
                  neovim
                ];
              };
            }
          );

          # Flake formatter. RFC style is modern, maintained and clean
          formatter = forAllSystems (
            system:
            let
              pkgs = mkPkgs system;
            in
            pkgs.nixfmt-rfc-style
          );

          inputs.self.submodules = true;
          # Enable binary caching
          # https://cache.forall.systems/
          nixConfig = {
            extra-substituters = [ "https://cache.forall.systems" ];
            extra-trusted-public-keys = [
              "cache.forall.systems:5PmD7QO4MSF8YgyRZtkSGXRDo96H3bybIf2SsQh8ScI="
            ];
          };
          nixosConfigurations = {
            # Provides the NixOS system configuration as an output of the flake.
            # Evaluated by nixos-rebuild when generating a new system configuration.
            # mkSystem provides a common interface to build any architecture,
            # updated with a set of modules specific for each machine.
            #
            # See update syntax: https://nix.dev/manual/nix/2.34/language/operators#update
            #
            # forAllSystems : (listOf str) systems
            #  ... mkNixosConfig : (str) system (str) hostname (listOf module) modules -> (attrSet) nixosSystem

            # lily = forAllSystems (
            #   system:
            #   mkNixosConfig system "lily" [
            #     # Additional optional system modules
            #     # ./modules/nixos/system/...
            #
            #     # Input nixos modules
            #     disko.nixosModules.disko
            #     nixos-hardware.nixosModules.apple-macbook-air-7
            #   ]
            # );

            # TODO: Fix the above and use it instead of the below
            lily = nixpkgs.lib.nixosSystem {
              modules = [
                # Include all machine-specific configuration
                # Each folder in ./machines corresponds to a physical host.
                # These should be generated by an initial nixos install (nixos-generate-config --root /mnt),
                # and stored in the ./machines/<hostname>/ directory,
                # along with a default.nix that loads all files in that directory.
                ./machines/lily

                # Include the Home-Manager configuration for the machine
                # Each file in ./homes corresponds to a physical host.
                # The file should be <hostname>.nix
                # This way the Home-Manager configuration may differ per machine,
                # typically only requiring importing different sets of home modules.
                home-manager.nixosModules.home-manager
                {
                  home-manager = {
                    backupFileExtension = "hm-backup";
                    extraSpecialArgs = { inherit inputs; };
                    useGlobalPkgs = true;
                    useUserPackages = true;
                    users.betty = ./homes/lily.nix;
                  };
                }

                # Include shared common system modules
                ./modules/nixos/system/common

                # Static module included to pull in overlays so that the configuration's pkgs
                # are actually modified as expected
                {
                  nixpkgs.overlays = overlays;
                }

                # Additional optional system modules
                ./modules/nixos/system/firefox.nix
                ./modules/nixos/system/greetd.nix
                ./modules/nixos/system/impermanance.nix
                ./modules/nixos/system/mango.nix
                ./modules/nixos/system/stylix.nix
                ./modules/nixos/system/sops.nix
                ./modules/nixos/system/tailscale.nix
                ./modules/nixos/system/virtualization.nix

                # Input nixos modules
                disko.nixosModules.disko
                nix-index-database.nixosModules.nix-index
                { programs.nix-index-database.comma.enable = true; }
                { programs.nix-ld.enable = true; }
                nixos-hardware.nixosModules.apple-macbook-air-7
                sops-nix.nixosModules.sops
              ];
              specialArgs = {
                inherit inputs outputs;
                lib = lib "x86_64-linux";
              };
            };

            # TODO: Fix the above and use it instead of the below
            lucy = nixpkgs.lib.nixosSystem {
              modules = [
                # Include all machine-specific configuration
                # Each folder in ./machines corresponds to a physical host.
                # These should be generated by an initial nixos install (nixos-generate-config --root /mnt),
                # and stored in the ./machines/<hostname>/ directory,
                # along with a default.nix that loads all files in that directory.
                ./machines/lucy

                # Include the Home-Manager configuration for the machine
                # Each file in ./homes corresponds to a physical host.
                # The file should be <hostname>.nix
                # This way the Home-Manager configuration may differ per machine,
                # typically only requiring importing different sets of home modules.
                home-manager.nixosModules.home-manager
                {
                  home-manager = {
                    backupFileExtension = "hm-backup";
                    extraSpecialArgs = { inherit inputs; };
                    useGlobalPkgs = true;
                    useUserPackages = true;
                    users.betty = ./homes/lucy.nix;
                  };
                }

                # Include shared common system modules
                ./modules/nixos/system/common

                # Static module included to pull in overlays so that the configuration's pkgs
                # are actually modified as expected
                {
                  nixpkgs.overlays = overlays;
                }

                # Additional optional system modules
                ./modules/nixos/system/firefox.nix
                ./modules/nixos/system/greetd.nix
                ./modules/nixos/system/icecast.nix
                ./modules/nixos/system/impermanance.nix
                ./modules/nixos/system/kde.nix
                ./modules/nixos/system/mango.nix
                ./modules/nixos/system/tailscale.nix
                ./modules/nixos/system/stylix.nix
                ./modules/nixos/system/sops.nix
                ./modules/nixos/system/virtualization.nix

                # Input nixos modules
                disko.nixosModules.disko
                nix-index-database.nixosModules.nix-index
                { programs.nix-index-database.comma.enable = true; }
                { programs.nix-ld.enable = true; }
                # Hardware config prebuilt optimisations for microsoft surface
                nixos-hardware.nixosModules.microsoft-surface-pro-intel
                sops-nix.nixosModules.sops
              ];
              specialArgs = {
                inherit inputs outputs;
                lib = lib "x86_64-linux";
              };
            };

            # TODO: Fix the above and use it instead of the below
            lulu = nixpkgs.lib.nixosSystem {
              modules = [
                # Include all machine-specific configuration
                # Each folder in ./machines corresponds to a physical host.
                # These should be generated by an initial nixos install (nixos-generate-config --root /mnt),
                # and stored in the ./machines/<hostname>/ directory,
                # along with a default.nix that loads all files in that directory.
                ./machines/lulu

                # Include the Home-Manager configuration for the machine
                # Each file in ./homes corresponds to a physical host.
                # The file should be <hostname>.nix
                # This way the Home-Manager configuration may differ per machine,
                # typically only requiring importing different sets of home modules.
                home-manager.nixosModules.home-manager
                {
                  home-manager = {
                    backupFileExtension = "hm-backup";
                    extraSpecialArgs = { inherit inputs; };
                    useGlobalPkgs = true;
                    useUserPackages = true;
                    users.betty = ./homes/lulu.nix;
                  };
                }

                # Include shared common system modules
                ./modules/nixos/system/common

                # Static module included to pull in overlays so that the configuration's pkgs
                # are actually modified as expected
                {
                  nixpkgs.overlays = overlays;
                }

                # Additional optional system modules
                ./modules/nixos/system/firefox.nix
                ./modules/nixos/system/greetd.nix
                # ./modules/nixos/system/impermanance.nix
                ./modules/nixos/system/mango.nix
                ./modules/nixos/system/samba.nix
                ./modules/nixos/system/sops.nix
                # ./modules/nixos/system/stylix.nix
                # ./modules/nixos/system/virtualization.nix
                ./modules/nixos/system/tailscale.nix

                # Input nixos modules
                disko.nixosModules.disko
                nix-index-database.nixosModules.nix-index
                { programs.nix-index-database.comma.enable = true; }
                { programs.nix-ld.enable = true; }
                nixos-hardware.nixosModules.common-cpu-amd
                # nixos-hardware.nixosModules.common-gpu-nvidia-kepler
                nixos-hardware.nixosModules.common-pc-ssd
                sops-nix.nixosModules.sops
              ];
              specialArgs = {
                inherit inputs outputs;
                lib = lib "x86_64-linux";
              };
            };
          };

          packages = forAllSystems (
            system:
            let
              pkgs = mkPkgs system;
            in
            (import ./pkgs {
              inherit pkgs inputs;
            })
          );
        };
        ######################
        # Original flake above
        systems = [
          "x86_64-linux"
        ];

        perSystem = { config, pkgs, ... }: { };

      }
    );

  inputs = {
    ## PACKAGE CHANNELS ##
    # Don't forget to periodically update the lockfile: nix flake update
    # Only do this when you're ready to fix any breaking changes, however

    # Primary nixpkgs repository: use unstable (latest rolling) by default
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    # Pinned nixpkgs to most recent stable, will be injected via an overlay
    # You may want to edit this pin to new stables periodically
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-25.11";

    #This is the url of the most up to date branch of nixpkgs.
    nixpkgs-bleeding.url = "github:NixOS/nixpkgs/master";
    ## PUBLIC INPUTS ##
    # Inputs are the package repositories of nix flakes.
    # Check out the many projects by nix-community or Mic92 on GitHub!
    #
    # When adding a new input, make sure to avoid channel duplication by including 'inputs.nixpkgs.follows = "nixpkgs";'
    # when necessary (check the README of whatever input you're adding).
    #
    # In order to consume the module in your nixosSystem, it must be included in the attrSet passed to outputs!
    #
    # I have added a large variety of recommended flakes to your inputs. Some are disabled for now to avoid bloat,
    # but I encourage you to check them out and enable if they seem cool. Just don't get too excited or things will start to take
    # a very long time to evaluate without beefier hardware (this much is already quite a lot so far).

    # Ableton Live on Linux
    ableton-linux = {
      url = "github:shibco/ableton-linux";
    };

    # Affinity Image Editor running through Wine Bottles
    affinity-nix = {
      url = "github:mrshmllow/affinity-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Modern desktop shell written in Quickshell QML
    caelestia-shell = {
      url = "github:caelestia-dots/shell";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative partitioning and formatting
    disko = {
      url = "github:nix-community/disko/latest";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Framework for using flakes
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
    };

    # Manage your user's $HOME in addition to the system
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # A scrollable tiling window manager with touchscreen support
    niri = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Persist & link data into your ephemeral root at boot time
    impermanence = {
      url = "github:nix-community/impermanence";
    };

    # Modern, featureful, lightweight wayland compositor
    mango = {
      url = "github:DreamMaoMao/mango";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # System utilities for music creation on nix (e.g. realtime audio optimisations)
    musnix = {
      url = "github:musnix/musnix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Provides a search index to improve 'package not found' help text when loading pkgs into a nix shell
    nix-index-database = {
      url = "github:Mic92/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Pure Nix Neovim configuration
    nixvim = {
      url = "github:nix-community/nixvim";
      # If using a stable channel you can use `url = "github:nix-community/nixvim/nixos-<version>"`
    };

    # Community-managed modular hardware configurations
    nixos-hardware.url = "github:NixOS/nixos-hardware";

    # Vibe coded flake.nix to wrap an osc-control utility
    osc-control = {
      url = "github:0tanh/osc-utility";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Community sourced, pre-configured git pre-commit hooks
    # Runs useful tools on pre-commit to lint & check for errors before creating a commit
    pre-commit-hooks = {
      url = "github:cachix/pre-commit-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Spicetify - customisable spotify
    spicetify-nix = {
      url = "github:Gerg-L/spicetify-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # SOPS-based secrets management
    sops-nix = {
      url = "github:mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Nix-powered centralised colortheming and style
    stylix = {
      url = "github:danth/stylix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # My todo-list
    todo = {
      url = "https://git.feline.fyi/0tanh/todo.git";
      flake = false;
    };

    # Browser based on firefox that I like a lot
    zen-browser = {
      url = "github:youwen5/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    ## PRIVATE INPUTS
    # We will use git+ssh (ssh-agent based) authentication to download git contents from private git repos.
    # This is where we can store additional data such as dotfiles or secrets for referencing elsewhere.

    # Private SOPS secrets repository
    secrets = {
      url = "git+ssh://git@github.com/0tanh/nix-secrets.git?ref=main&shallow=1";
      flake = false;
    };

    # Private dotfiles repository
    dotfiles = {
      url = "git+ssh://git@github.com/0tanh/dotfiles.git?ref=main&shallow=1";
      flake = false;
    };

  };
}
