# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  boot.kernel.sysctl = {
    "fs.inotify.max_user_watches" = 524288;
    "fs.inotify.max_user_instances" = 1024;
  };
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "wl"
  ];
  boot.extraModulePackages = [ pkgs.linuxKernel.packages.linux_6_18.broadcom_sta ];
  boot.zfs.forceImportRoot = false;

  nixpkgs.config = {
    allowUnfree = true;
    allowBroken = true;
    permittedInsecurePackages = [
      "broadcom-sta-6.30.223.271-59-6.18.33"
    ];
  };

  security.rtkit.enable = true; # Enables real-time scheduling priority

  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    jack.enable = true;
  };
  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/f71e1167-07e0-45c7-8013-72decf385604";
  #     fsType = "ext4";
  #   };
  #
  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/5F66-17ED";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };
  #
  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/673a76b4-9ecb-435b-8e24-84a3036f1ae8"; }
  #   ];

  fileSystems = {
    "/home" = {
      neededForBoot = true;
    };
    "/persist" = {
      neededForBoot = true;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
