# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a76fd4b9-8f65-4098-9f65-0012afd3a6a6";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a76fd4b9-8f65-4098-9f65-0012afd3a6a6";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a76fd4b9-8f65-4098-9f65-0012afd3a6a6";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/313A-B618";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];
  nixpkgs.config = {
    allowUnfree = true;
    nvidia.acceptLicense = true;
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Support NVIDIA GeForce GTX 650
  # load proprietary nvidia kernel modules for wayland and x11
  services.xserver.videoDrivers = lib.mkDefault [ "nvidia" ];
  # https://nixos.wiki/wiki/Nvidia
  hardware.nvidia = {
    # GTX 650 too old for nouveau
    open = false;
    # NVIDIA GeForce GTX 650 supported by driver 470.xx
    # https://www.nvidia.com/en-us/drivers/unix/legacy-gpu/
    # https://github.com/NixOS/nixpkgs/blob/0bb7750e6a12f4f945714cd9316b1f8cb9d48a53/pkgs/os-specific/linux/nvidia-x11/default.nix#L178
    package = config.boot.kernelPackages.nvidiaPackages.legacy_470;
    # enables loading kernel modules with modeset=1
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
    # of just the bare essentials.
    powerManagement.enable = false;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;
  };
}
